version: '3'

volumes:
  kitty_pg_data:
  static:

services:
  kitty_db:
    image: postgres:13
    env_file: .env
    volumes:
      - kitty_pg_data:/var/lib/postgresql/data
  kitty_backend:
    image: adelkhakimov/kitty_backend
    env_file: .env
    depends_on:
      - kitty_db
    volumes:
      - static:/kitty_backend
  kitty_frontend:
    image: adelkhakimov/kitty_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: adelkhakimov/kitty_nginx
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 9000:80
